name: Release Workflow

on:
  release:
    types:
      - created
      - deleted

jobs:
  run_on_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python packages
        run: |
          pip install PyGithub pandas

      - name: Fetch main branch
        run: git fetch origin main

      - name: Switch to main branch
        run: git checkout -B main origin/main

      - name: Execute Python script
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python generate_json.py -t ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          commit_options: '--no-verify --signoff'
          file_pattern: 'apps.json index.html bundleId.csv icons/*'
          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
          push_options: '--force'
