on:
  push:
    branches: ["main"]
  release:
    types:
      - published
      - deleted
      - edited
      - prereleased
      - released
      - created
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to the GitHub runner.
      
      # Add these lines to create and switch to a new branch.
      - name: Create and switch to a new branch
        run: |
          git checkout -b new-branch-name

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 # install the Python needed

      - name: Install Python packages
        run: |
          pip install PyGithub pandas

      - name: Execute Python script # run the run.py to get the latest data
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python generate_json.py -t ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: Automated Change
          commit_options: '--no-verify --signoff'
          file_pattern: 'apps.json index.html bundleId.csv icons/*'
          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
          push_options: '--force'
