name: Auto Commit and Push

on:
  push:
    branches:
      - main

jobs:
  auto_commit_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Auto Commit Action
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        REPOSITORY: .
        STATUS_OPTIONS: ''
        FILE_PATTERN_ADD: 'apps.json bundleId.csv icons/*'  # Change FILE_PATTERN to FILE_PATTERN_ADD
        BRANCH: ''

        ADD_OPTIONS: ''
        FILE_PATTERN_ADD: 'apps.json bundleId.csv icons/*'  # Change FILE_PATTERN to FILE_PATTERN_ADD

        COMMIT_OPTIONS: '--no-verify --signoff'
        COMMIT_USER_NAME: My GitHub Actions Bot
        COMMIT_USER_EMAIL: my-github-actions-bot@example.org
        COMMIT_MESSAGE: Automated Change
        COMMIT_AUTHOR: Author <actions@github.com>

        TAGGING_MESSAGE: ''

        PUSH_OPTIONS: '--force origin HEAD:main'
